version: '3.7'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    init: true
    ports:
      - 5601:5601
    networks: 
      - internal

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    init: true
    ports:
      - 9200:9200
    networks:
      - internal
    environment:
      - "node.name=es01"
      - "cluster.name=es-docker-cluster"
      - "discovery.type=single-node"

networks:
  internal: 
